### ISSUE TITLE
adding we_undo to the ContentDB (or merge it with WorldEdit)

### ISSUE THREAD

**Issue by Lemente** [HybridDog/we_undo#6]
I believe we_undo should be present on the ContentDB, since it is such an important feature.

Even better would be to merge it directly with Worldedit, if that's possible.

Thanks!

**Comment by HybridDog** [comment]
I added it to the ContentDB (Ready for Review) now.
Merging it into WorldEdit would be fine for me, but I doubt it would be accepted because the code can be simplified there and Pull Requests don't seem to get much attention, see for example https://github.com/Uberi/Minetest-WorldEdit/pull/92.
